### PR TITLE
Development

### PR DESCRIPTION
**Pull request by emil01**
I have added the INPUT_PULLUP functionality that will make adding switches and other such devices easier. 

Code has been compiled, uploaded and tested with the Arduino UNO

### CODE REVIEW

**Comment by carlosperate** [comment]
Thank you for the contribution @emil01.

I've been playing with this new block and while it does work well, I was thinking that maybe it is not very intuitive to use without knowing about the Arduino pin configuration.
If the user doesn't know about this feature it's not quite clear that this block on it's own has to be connected to the `digitalWrite` block, to then affect the `pinMode` code in the `setup()`.

So what do you think if instead we create a "set up block" (so no "previous" or "next" statements) for `pinMode()`, something along these lines:
https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#anfwtv

image

**Comment by emil01** [comment]
@carlosperate Yes you are right, it would make things easier. I will have this added in my next commit.

**Comment by carlosperate** [comment]
Great, thanks @emil01 !
Also, it would make the code merge a bit easier if the PR was submitted without the compiled files, as that will get out of sync from master quite quickly and cause merge conflicts.

**Comment by emil01** [comment]
Will do. Thanks

**Pull request closed without merging**
