### PR TITLE
Blockly4Arduino changes transferred to ardublockly

### PR DESCRIPTION
**Pull request by bmcage**
This is a large pull request in order to discuss the changes as present in Blockly4Arduino. Based on discussion it can be split in parts, or if you want to make me happy, one big PR :-)

This contains:

1. Fully translatable blockly part, and a Dutch translation. No interface stuff. Strings should start with ARD_ mostly, to make merging with future blockly changes more simple.

2. IO pins selectable as blocks in IO

3. variable versions of digital/analog read/write. This is very important for my use case, pins need to change going from UNO to a ATTINY chip, so writes have to be with a variable that is assigned a pin, not by selecting the pins in the read/write block. There is no need to expose this in ardublockly, though it would be better coding practice.

4. a declare section that allows declares to bool,int,uint,float, long, ulong or pins. Optional in the new block structure or by default. Personally I like it.

Some notes:

1. These changes are present in https://github.com/bmcage/blockly/tree/arduino, however, that is normal blockly, with a small hack to have the static typing added in ardublockly somewhat, but not 100%. This causes some issues, I need to determine how to handle the static typing there.

2. I could not build the translation with ardublockly build.py in blockly. Something is off, I build the translation in my blockly branch, and copied over.

TODO: Please comment on what parts you find useful, so as to make PR as per your requirement.

### CODE REVIEW

**Comment by carlosperate** [comment]
Sorry it's taking me this long to check this PR out, I've been a bit busier than I expected.
I'll see if I can review it tonight, maybe it will be easier to start integrating if it was broken down, but I'll be able to better advice there once I have a good look :)

Quick one, if there are no changes to the core blockly or the default blocks, I think these files can be reverted back to their original state:
```
blockly/python_compressed.js
blockly/php_compressed.js
blockly/javascript_compressed.js
blockly/dart_compressed.js
blockly/blockly_uncompressed.js
````

**Comment by bmcage** [comment]
I don't fully understand why they changed on running build.py. Because they did, they are in the PR. As said, let me know in due time what is useful and how it should change, so as to make specific PR for it.
If you want to test the blocks online while reading the PR (without static typing though !!!), you can do that here: http://ingegno.be/Manuals/Blockly4Arduino/blockly4Arduino/index_en.html

**Comment by carlosperate** [comment]
The build sometimes changes the ordering of the uncompressed files, but the most likely scenario here is that I currently don't recompile the compressed files with each update, as the build servers do that on each commit anyway for the downloadable executables (I do plan on doing "routine compiles" in a similar fashion to what Blockly does).

Once again, sorry it's taken all this time to review the PR, thanks again for submitting. Thanks for providing the online link as well, that has definitely saved me some time as well.

You bring up two important needs in Ardublockly at the moment:
* Having additional types representative of the standard C data types
* To be able to assign pins to variables.

For the first one, I think it's probably better to stick with the [casting block](https://github.com/carlosperate/ardublockly/blob/master/blockly/blocks/arduino/variables.js#L22) and to expand the Types available to include additional ones. Doing this should be a relatively easy addition to the [core/types.js](https://github.com/carlosperate/ardublockly/blob/master/blockly/core/types.js#L19-L23) file, or if used as a block extension, like in the [Grove blocks](https://github.com/carlosperate/ardublockly/blob/master/blocks/grove/extensions.js), it could be done as:
```
Blockly.Types.addType(typeName, basicType, compatibleTypes)
```
* __typeName__: An String to identify the name of the type.
* __basicType__: A `Blockly.Type.BasicTypes` object that defined its basic type
* __compatibleTypes__: An array of `Blockly.Type.Types` that this Type can be compatible with.

This is a functionality that I still need to develop and define properly in the wiki. As a quick note of the way I plan it will look, I've added this page with very brief notes that I should expand as I work on these features:
https://github.com/carlosperate/ardublockly/wiki/Create-Blocks-%C2%A6-Extending-Ardublockly

Now, in terms of assigning a pin to a variable, this is something I've given some though in the past. I considered having a "pin block" (pretty much a tiny block with a dropdown listing all the pins), so that it could be assigned to a variable, and then all the "pin related blocks" would have a block input instead of the pin dropdown. While flexible, this type of implementation would require to do a lot more checks on every "workspace change event", to be able to check which type of pin the block requires (pwm, analogue, digital, etc), and if incorrect, all it can do is to attach warnings to the block. I'm personally not a big fan of having as many "warnings" as we currently have, and I much prefer to design blocks in a way in which incorrect configuration would just not be possible. So that being said, your approach is a lot more robust to this, and I quite like the idea of being able to use variables for pins.

What do you think about having like the "Define `item` as digital input `0`", which requires a block per pin type (and would not be extensible), we instead have a block with 2 drop down, one to select the "pin type" and the one already there to select the pin? Becoming "Define `item` as `digital input`  `0`".
Then we could modify any "pin related" block to have these variables attached to their dropdown in addition to the pins. So for example, the "analogue pin X" block would have the following options on the dropdown:

```
A0
A1
A2
A3
A4
A5
item
```

Thoughts?

**Comment by bmcage** [comment]
I find the casting block very 'programming like'. It is nice, but to explain it in a class as opposed to explaining a define block ..... If we do `item = millis()`, will we automatically infer item should be ulong, or should there be a cast there? The usecase of item=millis() to do computation of LED effect based on timing is my usecase to add the Define blocks. If you could make it clear how that would work in the casting paradigm, it would be clear to me what you mean. So the blink no delay example in Arduino, first link I find on CodeBender: https://codebender.cc/sketch:243739#blink%20no%20delay.ino 
So Previous is global, Current is in the loop and could be replaced with calling millis() itself all the time.

Your solution for pin assignment looks great to me. I would have liked something like that, but I don't know how to expand the drop down box, so I went the route I took. For this solution, having a Type for the possible types of pin makes sense too I think. Then you don't allow for example to assign a non PWM pin to a Servo block, ...

**Comment by carlosperate** [comment]
One of the things I was hoping to avoid was the need to clearly define from the beginning why a "number data type" can actually have different sizes, and the cast block was added not so much for a general initial use, but for more "advance" uses that might require it. Alternatively it is a good way to ensure a variable is set to a especific type, as there is no "guessing", the cast block will try assign the selected type.

I do see your point though, I think I underestimated the need for "large" integers, so we need a long int to be by default provided in Ardublockly, or things like millis will only count up to 32s. This can then be then be selected directly by the blocks that need it, so there should not need to be an explanation as there should not be any cast, the variable should automatically pick that up. This brings a different issue with promoting, I think I need to include that into the logic, so that promoting can be done when a variable needs a "larger value" (harder to decide for floats/doubles, do we really need doubles?).

**Comment by bmcage** [comment]
Large integers defenitely needed.
In my view, Ardublockly should be able to do the tutorial examples of Arduino, https://www.arduino.cc/en/Tutorial/BuiltInExamples
The 6th one has a float: https://www.arduino.cc/en/Tutorial/ReadAnalogVoltage
Due to integer division, if you write there float voltage = sensorValue * (5 / 1023); it already doesn't work anymore. If voltage becomes int, we only have a 6 levels between 0 and 5.

Otherwise no real use of float in the examples, thought the distance sensor would be better if it was in float instead of long in the tutorial. Something like a distance sensor we might be able to hide in a block though.

So, to conclude, as expected double not needed much, but if, then needed for computations: conversion to voltages, distances based on readings on the pins.

**Comment by carlosperate** [comment]
I think you make good point there, we should try to aim to have all the built-in examples possible in Ardublockly, ideally adding them to the examples folder. I was already planning to update the way examples are selected on the front end as part to go in a similar "window/modal" as what the "additional blocks" have.

I'll add long integers next and leave it to only floats (no doubles) for now.

**Comment by bmcage** [comment]
I made pull request #56 for the translation part. 
Do I suggest some other changes for inclusion too or not? I would leave it to you at the moment to work out how you do the declare and to assign pins to variables. If I can help in some way for that, let me know. 
At the moment, I will use extra functions like declare and var in Blockly4Arduino, and then move to whatever 'final' version we come up with.
I would suggest you close this PR then.

**Comment by bmcage** [comment]
I cleaned up my branches, in case you want the old PR code, it is in my branch old_master, master now tracks your code instead.
The same changes are present too in branch blockly4arduino https://github.com/bmcage/ardublockly/tree/blockly4arduino in which I will test out some ideas.

**Pull request closed without merging**
